categories:
  A: "1"

metrics:
  deltaT_avg: "float(numpy.mean([{tL}.Eval(4), {tR}.Eval(4), {bL}.Eval(4), {bR}.Eval(4)]))"

read:
  tL: "g_DeltaTTopL"
  tR: "g_DeltaTTopR"
  bL: "g_DeltaTBottomL"
  bR: "g_DeltaTBottomR"

values:
  dummy: 1